before:
  hooks:
    - make man-pages
    - make autocomplete-scripts
    - go mod tidy
    - docker login -u {{ .Env.DOCKERHUB_USERNAME }} -p {{ .Env.DOCKERHUB_TOKEN }}

builds:
  - main: ./cmd/gitlab-ci-pipelines-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath

universal_binaries:
  - {}

#archives:
#  - name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
#    rlcp: true
#    format_overrides:
#      - goos: windows
#        format: zip
#    files:
#      - README.md
#      - LICENSE
#      - helpers/*

dockers:
  - image_templates:
      - 'docker.io/thuongnn1997/gitlab-ci-pipelines-exporter:{{ .Tag }}-amd64'
    ids: [gitlab-ci-pipelines-exporter]
    goarch: amd64
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/thuongnn/gitlab-ci-pipelines-exporter
      - --label=org.opencontainers.image.source=https://github.com/thuongnn/gitlab-ci-pipelines-exporter
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

docker_manifests:
  - name_template: docker.io/thuongnn1997/gitlab-ci-pipelines-exporter:{{ .Tag }}
    image_templates:
      - docker.io/thuongnn1997/gitlab-ci-pipelines-exporter:{{ .Tag }}-amd64

changelog:
  skip: true
